[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "quantum-rl-jax"
version = "0.0.1"
description = "Reinforcement learning algorithms with variational quantum circuits"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "Enric Ribera Borrell", email = "ribera.borrell@gmail.com"}
]
classifiers = [
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.10,<3.14"
dependencies = [
    "tyro",
    "matplotlib",
    "jax",
    "flax",
    "optax",
    "orbax-checkpoint",
    "gymnax==1.0.0",
    "jumanji",
    "pennylane",
    "jupyterlab",
]

[project.urls]
Homepage = "https://github.com/riberaborrell/quantum-rl-jax"
"Bug Tracker" = "https://github.com/riberaborrell/quantum-rl-jax/issues"

[project.optional-dependencies]
dev = ["pytest"]

[tool.setuptools.packages.find]
where = ["src"]
